// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Prelude = require("./prelude.bs.js");
var Sub$BsOakCore = require("@bs-oak/core/lib/js/src/sub.bs.js");
var Html$BsOakHtml = require("@bs-oak/html/lib/js/src/html.bs.js");
var Property$BsOakHtml = require("@bs-oak/html/lib/js/src/property.bs.js");
var Browser$BsOakBrowser = require("@bs-oak/browser/lib/js/src/browser.bs.js");

function set(param_0) {
  return /* Set */[param_0];
}

function init() {
  return Prelude.$unknown$bang(4, /* [] */0);
}

function update(msg, model) {
  if (typeof msg === "number") {
    switch (msg) {
      case 0 : 
          return Prelude.$unknown$bang(model + 1 | 0, /* [] */0);
      case 1 : 
          return Prelude.$unknown$bang(model - 1 | 0, /* [] */0);
      case 2 : 
          return Prelude.$unknown$bang(0, /* [] */0);
      
    }
  } else {
    return Prelude.$unknown$bang(msg[0], /* [] */0);
  }
}

function view(model) {
  return Html$BsOakHtml.div(/* [] */0, /* :: */[
              Html$BsOakHtml.span(/* :: */[
                    Property$BsOakHtml.style(/* :: */[
                          /* tuple */[
                            "text-weight",
                            "bold"
                          ],
                          /* [] */0
                        ]),
                    /* [] */0
                  ], /* :: */[
                    Html$BsOakHtml.text(Prelude.$$String[/* from_int */0](model)),
                    /* [] */0
                  ]),
              /* :: */[
                Html$BsOakHtml.br(/* [] */0, /* [] */0),
                /* :: */[
                  Html$BsOakHtml.button(/* :: */[
                        Property$BsOakHtml.on_click(/* Increment */0),
                        /* [] */0
                      ], /* :: */[
                        Html$BsOakHtml.text("Increment"),
                        /* [] */0
                      ]),
                  /* :: */[
                    Html$BsOakHtml.br(/* [] */0, /* [] */0),
                    /* :: */[
                      Html$BsOakHtml.button(/* :: */[
                            Property$BsOakHtml.on_click(/* Decrement */1),
                            /* [] */0
                          ], /* :: */[
                            Html$BsOakHtml.text("Decrement"),
                            /* [] */0
                          ]),
                      /* :: */[
                        Html$BsOakHtml.br(/* [] */0, /* [] */0),
                        /* :: */[
                          Html$BsOakHtml.button(/* :: */[
                                Prelude.$less$pipe(Property$BsOakHtml.on_click, /* Set */[42]),
                                /* [] */0
                              ], /* :: */[
                                Html$BsOakHtml.text("Set to 42"),
                                /* [] */0
                              ]),
                          /* :: */[
                            Html$BsOakHtml.br(/* [] */0, /* [] */0),
                            /* :: */[
                              model !== 0 ? Html$BsOakHtml.button(/* :: */[
                                      Property$BsOakHtml.on_click(/* Reset */2),
                                      /* [] */0
                                    ], /* :: */[
                                      Html$BsOakHtml.text("Reset"),
                                      /* [] */0
                                    ]) : Html$BsOakHtml.div(/* [] */0, /* [] */0),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function main(param) {
  return Browser$BsOakBrowser.element(init, update, view, (function () {
                return Sub$BsOakCore.none;
              }), param);
}

var increment = /* Increment */0;

var decrement = /* Decrement */1;

var reset = /* Reset */2;

exports.increment = increment;
exports.decrement = decrement;
exports.reset = reset;
exports.set = set;
exports.init = init;
exports.update = update;
exports.view = view;
exports.main = main;
/* Prelude Not a pure module */
