// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Cmd$BsOakCore = require("@bs-oak/core/lib/js/src/cmd.bs.js");

function from_int(prim) {
  return String(prim);
}

var $$String$1 = /* module */[/* from_int */from_int];

function $pipe$great(f, g) {
  return Curry._1(g, f);
}

function $less$pipe(prim, prim$1) {
  return Curry._1(prim, prim$1);
}

function $unknown$bang(model, cmds) {
  return /* tuple */[
          model,
          Cmd$BsOakCore.batch(cmds)
        ];
}

var Attr = 0;

var Browser = 0;

var Cmd = 0;

var Html = 0;

var Sub = 0;

exports.Attr = Attr;
exports.Browser = Browser;
exports.Cmd = Cmd;
exports.Html = Html;
exports.Sub = Sub;
exports.$$String = $$String$1;
exports.$pipe$great = $pipe$great;
exports.$less$pipe = $less$pipe;
exports.$unknown$bang = $unknown$bang;
/* Cmd-BsOakCore Not a pure module */
